Back 6
hhru/hh-career-solution pull request #14
Opened 2021-04-16 10:36 UTC by BorisVeprintzev

Открыл занаво, чтоб выбросить большенство обсуждений, которые уже не актуальны. Почему-то git пометил все файлы как новые.

2021-04-16 11:18 UTC, Azadios commented
Кажись я понял в чём дело. Ты уверен, что ты back-6 ребейснул на master, а не наоборот?

2021-04-16 12:42 UTC, BorisVeprintzev commented
нет)

2021-04-16 13:15 UTC, Azadios commented
Ну на гх коммиты есть, так что не потеряются. Попробуешь восстановить? На крайняк можно черри-пиком собрать)))))

2021-04-17 11:59 UTC, BorisVeprintzev commented
нет похоже я переносил все таки делал rebase на мастера. Я сделал еще раз через консоль чтоб точно на мастера было, результат тот же самый.

2021-04-17 12:42 UTC, Azadios commented
Если найдёшь время на созвон в ближайшие 2 часа, то можем вместе решить

2021-04-19 03:45 UTC, Azadios reviewed
Отличный код. По логике почти не осталось вопросов, кроме того места с использованием null. В основном замечания по оформлению. Заодно проверь плагином, можешь через mvn validate.

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/GenericDao.java
> +package ru.hh.career.solution.professionalenvironmentandspecialization.dao;
Лучше воспользуйся моим GenericDao. Там функционал такой же, он в ru.hh.career.solution.dao. DRY, все дела

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/ProfessionalEnvironmentDao.java
> +public class ProfessionalEnvironmentDao extends GenericDao{
Всё таки давай, как Никита предложил, не создавать специальные дао, если нужен только CRUD. Можно GenericDao воспользоваться, он не абстрактный теперь

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/SpecializationDao.java
> +public class SpecializationDao extends GenericDao {
Тож самое - используй GenericDao

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +public class ParserProfessionalEnvironmentAndSpecialization {
Перенесёшь Parser в конец названия, плз?

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +        }
Сначала используешь, потом проверяешь на null. [В доках](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.InputStream-) нет явного упоминания, что null обрабатывается, так что лучше не пытать судьбу

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +        is.close();
Почитай про try-with-resources. Думаю, здесь отлично подходит.

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +        return profEnvDTOFuture.get();
Можешь убрать создание переменной, сократишь запись

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/ProfessionalEnvironmentEntity.java
> +public class ProfessionalEnvironmentEntity {
Можно и без Entity в названии

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/SpecializationsDto.java
> +    private Integer idProfessionalEnvironment;
id бы в конец названий + specializationId можно сделать просто id, ведь оно и так в классе SpecializationDto

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/ProfessionalEnvironmentEntity.java
> +    private String professionalEnvironmentName;
Просто name. В табличке тож стоит убрать приставку professional_environment, она уже есть в названии таблицы, незачем и на колонках повторять. Заодно и `@Column` можешь убрать, потому что имена одинаковые получатся

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/SpecializationEntity.java
> +@Table
Имя таблицы забыл прописать?

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/SpecializationEntity.java
> +public class SpecializationEntity {
Entity можно убрать

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/SpecializationEntity.java
> +    private Integer specializationId;
Повторяешь имя класса

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +@Transactional
Спусти на уровень метода, чтобы в будущем можно было не `@Transactional` метод в этом классе создать.

2021-04-19 03:45 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +@Singleton
Зачем?

2021-04-19 06:16 UTC, colorbash reviewed
где таблицы очищаются чтобы 2 раза не записывать? или проверка на существование данных в таблицах? чтобы не делать лишнюю работу...

я вроде добавлял чекстайл, не должно собираться при 4 пробельном отступе, неужели не работает? следует все привести к 2му отступу.

А так в целом все почти норм, на финишной прямой, давай пока свежо в голове добьем этот пр по быстрому :)

2021-04-19 06:16 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/SpecializationsDeserializer.java
> +public class SpecializationsDeserializer extends StdDeserializer<SpecializationsDto> {
SpecializationDeserializer

2021-04-19 06:16 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ProfessionalEnvironmentDeserializer.java
> +    static final ObjectMapper mapper = new ObjectMapper();
`private static final ObjectMapper MAPPER = new ObjectMapper();`

2021-04-19 06:16 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/ProfessionalEnvironmentEntity.java
> +        if (this != o) {
else загромаждает код, смотри как девственно чисто получилось
```java
public boolean equals(Object o) {
        if (this != o) {
            if (o != null && getClass() == o.getClass()) {
                ProfessionalEnvironmentEntity that = (ProfessionalEnvironmentEntity) o;
                return getId().equals(that.getId()) && getProfessionalEnvironmentName().equals(that.getProfessionalEnvironmentName());
            } 
            return false;
        }
        return true;
    }
```

2021-04-19 06:16 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +    public void mainParser() throws IOException, ExecutionException, InterruptedException {
где и когда вызывает mainParser?

2021-04-19 06:16 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +                specializationDao.save(specializationEntity);
попробуй сохранять сразу коллекции а не по однму, это быстрее, мы всегда стараемся передавать по хттп и сохранять\брать в\из базы батчами

2021-04-19 06:16 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +        for (ProfessionalEnvironmentDto professionalEnvironmentDto : professionalEnvironmentDtos) {
2 вложенных фора в методе не приветствуется, сложно читать, разбей плиз на методы, увидишь, намного проще будет читаться

2021-04-23 08:55 UTC, k-vasiliev commented on backend/init.sql
> +  specialization_id INTEGER PRIMARY KEY,
Вообще называть PK вида {table_name}_id довольно удобно, потому что позволяет потом писать джойны вида 
`INNER JOIN specialization USING (specialization_id)` без `ON ...`

2021-04-23 09:06 UTC, k-vasiliev commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +    static final ObjectMapper mapper = new ObjectMapper();
Я бы рекомендовал вообще маппер вынести куда-то в одно место (фабрику/бин). Потому что иногда приходится маппер доконфигурировать (добавить `FAIL_ON_UNKNOWN_PROPERTIES`, зарегистрировать `JavaTimeModule` и т.д.) и хочется не искать мапперы по всему проекту

2021-04-23 09:17 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +    static final ObjectMapper mapper = new ObjectMapper();
Привет, Кирилл, приятно видеть тебя в нашем проекте :) Прям повторил моё предложение, тож думаю, что стоит так сделать

2021-04-23 09:18 UTC, Azadios commented on backend/init.sql
> +  specialization_id INTEGER PRIMARY KEY,
Да, мы это обсуждали. Решили, что нам пока такое не нужно, а если будет нужно, то лучше явно через `ON ...`

2021-04-23 11:02 UTC, BorisVeprintzev commented on backend/init.sql
> +  specialization_id INTEGER PRIMARY KEY,
могу я все-таки в этом плане настоять на своем, просто у меня уже был неудачный опыт когда в нескольких таблицах были одинаковые имена, как минимум несколько уменьшает читабельность при Join. Да и ничего плохого в том, что явно прописано что именно за id или name, я лично не вижу. Возможно чего-то не понимаю, буду рад если напишешь, чем это может быть неудобно.

2021-04-23 11:17 UTC, Azadios commented on backend/init.sql
> +  specialization_id INTEGER PRIMARY KEY,
Честно говоря, из неудобств я вижу только длинные названия. Но вообще, твоя же таска, так что
>могу я все-таки в этом плане настоять на своем

можешь :)

2021-04-23 13:43 UTC, BorisVeprintzev commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/SpecializationEntity.java
> +public class SpecializationEntity {
из названия имешь ввиду?

2021-04-23 13:56 UTC, BorisVeprintzev commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/ProfessionalEnvironmentDao.java
> +public class ProfessionalEnvironmentDao extends GenericDao{
не очень понял, просто в одном классе все хранить, т.е два разных сохранения или как не очень понял?

2021-04-23 14:04 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/ProfessionalEnvironmentDao.java
> +public class ProfessionalEnvironmentDao extends GenericDao{
Не, смотри, у GenericDao есть crud'ы, которые ты можешь использовать для любого класса. Это либо generic get, либо принимающие Object методы. Вот ими ты можешь сделать всё, что нужно, не создавая специальный дао под класс

2021-04-23 14:05 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/SpecializationEntity.java
> +public class SpecializationEntity {
Ага

2021-04-23 14:39 UTC, BorisVeprintzev commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +                specializationDao.save(specializationEntity);
правильно ли я понимаю, что необходимо создать список entity, и просто запихнуть его в save? или нужно где-то хиберу отдельно указывать что записываешь лист?

2021-04-23 16:47 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +                specializationDao.save(specializationEntity);
да, примерно так, в save, там же сигнатура метода, должна быть IDEподсвечена

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dao/CheckerOnNullDAO.java
> +public class CheckerOnNullDAO extends GenericDao {
CheckerOnNullDao

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dao/CheckerOnNullDAO.java
> +  public boolean checkOnNullDAO() {
может isSpecialisationsAbsent()

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dao/CheckerOnNullDAO.java
> +public class CheckerOnNullDAO extends GenericDao {
можно оставить это название дао если потом в нем проверять наличие регионов, обычно мы называем дао в честь сущностей, а логика в сервисе находится

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dao/GenericDao.java
> +public class GenericDao {
зачем еще одно GenericDao? есть же ru.hh.career.solution.dao.GenericDao

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +public class ParserProfessionalEnvironmentAndSpecialization {
ProfessionalEnvironmentParser

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +  static final ObjectMapper mapper = new ObjectMapper();
private static final ObjectMapper MAPPER = new ObjectMapper();

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +  static final ObjectMapper mapper = new ObjectMapper();
форматируем статические поля по стайлгайду

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +  static final ObjectMapper mapper = new ObjectMapper();
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +      System.out.println("Ошибка в программе: файл " + pathToProperties + " не обнаружено");
System.out.println надо заменить на вызов логгера
`LOGGER.error(" text {} {} ", pathToProperties, e)`

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +      e.printStackTrace();
напечатем тело исключения в логгере

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +    HttpClientFactory http = new HttpClientFactoryBuilder(new SingletonStorage<>(() ->
мы же договорились - жклиент в бин вынесем, инитить его при каждом запуске нехорошо
HttpClientFactory надо сделать бином

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +    CompletableFuture<ProfessionalEnvironmentDto[]> profEnvDTOFuture = http.with(request)
```
return http.with(request).expectJson(mapper, ProfessionalEnvironmentDto[].class).result().get();
```

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/SpecializationDto.java
> +  private Integer idSpecialization;
specializationId,
professionalEnvironmentId

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/resource/ParserResource.java
> +  @Path("/specialization")
это для теста, в мастер не должно попасть, надо убрать

2021-05-04 17:53 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/services/ParserSpecializationService.java
> +  public void mainParser() throws IOException, ExecutionException, InterruptedException {
вопрос открыт, кто вызывает mainParser ? надо привязать его вызов к старту приложения

2021-05-05 13:24 UTC, BorisVeprintzev commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/services/ParserSpecializationService.java
> +  public void mainParser() throws IOException, ExecutionException, InterruptedException {
разве мы не решили что через ендпоинты будем реализовывать?

2021-05-05 13:36 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/services/ParserSpecializationService.java
> +  public void mainParser() throws IOException, ExecutionException, InterruptedException {
Вероятно ты с @Azadios разговариавал на эту тему..
через ендпоинты удобно тестить, но в бою должно запускаться само, иначе забудут дернуть на демо все полетит в ...

2021-05-05 14:12 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/services/ParserSpecializationService.java
> +  public void mainParser() throws IOException, ExecutionException, InterruptedException {
Я тут подумал, можно в целом в конфигу засунуть, тогда при стартапе наба будет фетчить дату. Логически не самое верное решение, но зато никто не забудет 100%

2021-05-08 15:36 UTC, BorisVeprintzev commented
@Azadios @colorbash готово

2021-05-08 15:55 UTC, Azadios requested changes
Ещё немного по мелочи, но с checkstyle violation нельзя в мастер. Поправь и можно вливать

2021-05-08 15:55 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/config/BeanConfig.java
> +      System.out.println("Ошибка в программе: файл " + pathToProperties + " не обнаружено");
System.out ты фиг прочтёшь у сервиса, лучше в логи, но эт на будущее, тут в целом не критично

2021-05-08 15:55 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dao/GenericDao.java
> +public class GenericDao {
Так ты в итоге переехал на основной GenericDao? Тогда забыл удалить этот.

2021-05-08 15:55 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dao/CheckerOnNullDAO.java
> +public class CheckerOnNullDAO extends ru.hh.career.solution.dao.GenericDao {
И здесь не придётся указывать полный путь по пакетам, а можно будет через импорт. И `DAO` -> `Dao` поменять желательно

2021-05-08 15:55 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/services/ParserSpecializationService.java
> +  public ParserSpecializationService(GenericDao genericDao, CheckerOnNullDAO checkerOnNullDAO, ProfessionalEnvironmentParser professionalEnvironmentParser) {
![image](https://user-images.githubusercontent.com/41588457/117545390-42c31f00-b02e-11eb-951f-0272b8f34286.png)

2021-05-08 15:55 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dao/CheckerOnNullDAO.java
> +    return resultCount > 0;
Мож я чего неправильно понял, но тут разве не `resultCount == 0`, ну или `isSpecialisationsPresent()`

2021-05-08 16:15 UTC, BorisVeprintzev commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dao/CheckerOnNullDAO.java
> +    return resultCount > 0;
если таблица не пуста, тогда true и ничего не подгружается

2021-05-08 16:46 UTC, Azadios approved these changes

2021-05-08 19:03 UTC, colorbash approved these changes
Еее, добили!
поправь 2 последних мелочи, засквошь и мерж в мастер

2021-05-08 19:03 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironment/dto/ProfessionalEnvironmentParser.java
> +  public ProfessionalEnvironmentParser(HttpClientFactory http) {
навесить `@inject`

2021-05-08 19:03 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/config/BeanConfig.java
> +      jClientProperty.load(fileInputStream);
Можно сразу заинлайнить чтобы 51 сточку убрать
`jClientProperty.load(new FileInputStream(pathToProperties));`

2021-05-08 19:58 UTC, merged