Back 6
hhru/hh-career-solution pull request #7
Opened 2021-04-04 14:23 UTC by BorisVeprintzev

Пока не претендую на pull просто самый простой способ, чтоб привлечь внимание.

Пока только качаю и десериализую, нужно ли подключать к бд?? откуда лучше вызывать?

2021-04-05 04:23 UTC, Azadios reviewed
Вообще, учитывая, что это словарь, который, вроде, изменяться не часто будет, то можно сохранить in-memory. Но я тут точно не подскажу, лучше пусть @colorbash скажет

2021-04-05 04:23 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/PPEAS.java
> +package ru.hh.career.solution.parseProfEnvAndSpec;
Обычно директории в lowercase пишут

2021-04-05 04:23 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/PPEAS.java
> +        ObjectMapper mapper = new ObjectMapper(); // create once, reuse
Отличное замечание насчёт reuse. Предлагаю сделать бин с ObjectMapper, чтобы по проекту было одинаковое форматирование json. Бин в конфигу просто засунь. [Так](https://github.com/Azadios/hh-backend-homework/blob/master/backend/src/main/java/ru/hh/school/config/CommonConfig.java) я сделал в бэкэндовой домашке. Но тут скорее вопрос к @colorbash как лучше

2021-04-05 04:23 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/PPEAS.java
> +public class PPEAS {
PPEAS?

2021-04-05 04:23 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/ProfEnvDTO.java
> +@JsonDeserialize(using = SpecDeserializer.class)
И вот это можно записать прямо в ObjectMapper, если он будет один на проект

2021-04-05 04:23 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/ProfEnvDTO.java
> +public class ProfEnvDTO {
Тоже вопрос насчёт форматирования. Это, конечно, аббревиатура, но в какой-то степени ломает CamelCase. @colorbash вы как в хх делаете?

2021-04-05 04:23 UTC, Azadios commented on backend/src/test/java/ru/hh/career/solution/parseProfEnvAndSpec/TestParseJson.java
> +        String test = """
Лайк за текстовый блок :)

2021-04-05 04:23 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/PPEAS.java
> +        this.value = mapper.readValue(url, ProfEnvDTO[].class);
Я так понимаю, что у нас несколько задач на обращение к api.hh. Может лучше использовать отдельный клиент для этого? Например, [feign](https://github.com/OpenFeign/feign)

2021-04-05 06:43 UTC, colorbash commented
лучше сохранять в базу, тк в ней будут идшки специализаций, когда руками будем sql-ить, легче будет разобраться что есть что, делать это нужно либо при старте приложения, при этом перетирая старую таблицу, либо навесить эту задачу на отдельный goal в мавене для exec плагина и вызывать тогда когда нужно...

2021-04-05 06:43 UTC, colorbash commented on backend/pom.xml
> +        <dependency>
роверь плиз, джексон в набе должен быть, не надо его тянуть отдельно

2021-04-05 06:43 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/SpecDTO.java
> +    private Double id;
не оч хорошая идея в дабле хранить ид
типы данных с плавующей запятой нельзя сравнивать друг с другом на строгое равенство...
из-за их внутреннего представления как мантисы и порядка
давай лучше 2 инта `profAreaId` и `specializationId`

2021-04-05 06:43 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/SpecDTO.java
> +public class SpecDTO {
мы char-ы не экономим :) давай все полностью писать

2021-04-05 06:43 UTC, colorbash commented on backend/src/test/java/ru/hh/career/solution/parseProfEnvAndSpec/TestParseJson.java
> +}
тесты немного не так должны работать :)
они автоматом должны падать при сборке если не прошли, это можно сделать с помошью assert методов
ты прост выводишь в консоль, каждый раз сравнивать инфу глазами никто не будет...

Да и в целом ты тестишь метод десериализации, который по сути должен работать без нареканий, тк взят из библиотеки, в которой есть свои ЮТ, проверяющие его работу

2021-04-05 06:43 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/ProfEnvDTO.java
> +public class ProfEnvDTO {
стараемся в пакет `.dto.` положить, если не выходит пишем `ProfAreaDto`

2021-04-05 06:43 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/Main.java
> +
лишний дифф

2021-04-05 06:43 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/PPEAS.java
> +        this.value = mapper.readValue(url, ProfEnvDTO[].class);
или например https://github.com/hhru/jclient-common который уже должен быть в поставке наба

2021-04-05 06:43 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/PPEAS.java
> +        ObjectMapper mapper = new ObjectMapper(); // create once, reuse
можно, у нас чаще всего с этим не заморачиваются, в классе где он нужен прописывают статический маппер и все

2021-04-06 14:04 UTC, BorisVeprintzev commented on backend/pom.xml
> +        <dependency>
роверь?

2021-04-06 14:10 UTC, Azadios commented on backend/pom.xml
> +        <dependency>
Скорее всего там просто "П" пропущено :) И да, в набе есть джексон, не нужно тянуть отдельно

2021-04-10 14:11 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
>      private ProfessionalEnvironmentDTO[] value;
```suggestion
    private ProfessionalEnvironmentDto[] value;
```

2021-04-10 14:11 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
> +        return this.getValue();
А зачем тогда это Value? Да и не стоит, наверное, хранить состояние конкретного объекта в парсере.

2021-04-10 14:11 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ProfessionalEnvironmentDeserializer.java
> +        SpecializationsDto[] specDTOS = objectMapper.readValue(treeNode.get("specializations").toString(), SpecializationsDto[].class);
А тут точно toString должен быть, а не asText?

2021-04-12 05:06 UTC, colorbash commented on backend/init.sql
> +);
пустая строка в конце нужна

2021-04-12 05:08 UTC, colorbash commented on backend/init.sql
> +  professional_environment_id INTEGER PRIMARY KEY,
зачем в названиях полей дублировать имя таблицы?

2021-04-12 05:10 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
> +        Request request = new RequestBuilder("GET").setUrl("https://api.hh.ru/specializations").build();
api.hh.ru в константу бы, потом понадобится, а без https не будет работаеть?

2021-04-12 05:11 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
> +import ru.hh.jclient.common.*;
.* мы не приветствуем )

2021-04-12 05:11 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
> +        ObjectMapper mapper = new ObjectMapper();
в статик константу

2021-04-12 05:13 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/SpecializationsDto.java
> +@JsonDeserialize(using = SpecializationsDeserializer.class)
зачем нам JsonDeserialize ?

2021-04-12 05:16 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/SpecializationsDto.java
> +    private Integer id;
удобно было бы и professional_environment_id тут держать

2021-04-12 05:18 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/SpecializationsDto.java
> +@JsonDeserialize(using = SpecializationsDeserializer.class)
при сериализации и десериализации будут разные обьекты, что не есть хорошо...
можно хранить начальный ид `11.22` в поле - строке, а в SpecializationsDeserializer инитить 2 интовых поля ид

2021-04-12 05:25 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/entity/ProfessionalEnvironmentEntity.java
> +    private String envName;
сокращать не надо

2021-04-12 05:27 UTC, colorbash commented on backend/src/test/java/ru/hh/career/solution/parseProfEnvAndSpec/TestParseJson.java
> +}
тесты нужны на бизнес логику, в этой задаче можно не писать, смотри комент выше

2021-04-12 05:55 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
> +import ru.hh.jclient.common.*;
Вчера, кстати, с Димой это проблему в IDEA решали. Она сама собирает импорты в wildcard. [Здесь](https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports) можешь глянуть как убрать это

2021-04-12 11:05 UTC, BorisVeprintzev commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
> +        Request request = new RequestBuilder("GET").setUrl("https://api.hh.ru/specializations").build();
по инструкции делал, еще не проверял

2021-04-12 11:39 UTC, BorisVeprintzev commented on backend/init.sql
> +  professional_environment_id INTEGER PRIMARY KEY,
а как лучше?

2021-04-12 11:43 UTC, BorisVeprintzev commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
> +        ObjectMapper mapper = new ObjectMapper();
почему то ругается на static final, или я что то не так делаю?

2021-04-12 11:47 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
> +        ObjectMapper mapper = new ObjectMapper();
Из метода в класс вынес?

2021-04-12 11:50 UTC, Azadios commented on backend/init.sql
> +  professional_environment_id INTEGER PRIMARY KEY,
С одной стороны здорово иметь, скажем, environment_id, чтобы в запросах ручками не писать "id as environment_id", если нужно заджойнить, с другой стороны получилось довольно длинное название. Про как лучше это к @colorbash

2021-04-12 11:51 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/parseProfEnvAndSpec/dto/ParseProfessionalEnvironmentAndSpecialization.java
> +        Request request = new RequestBuilder("GET").setUrl("https://api.hh.ru/specializations").build();
А чем плохо по https? Или там по умолчанию на https ведёт?

2021-04-12 14:35 UTC, Azadios requested changes
У тебя очень давно ветка не обновлялась. Ребейснись на мастер. fast-forward не должен больно сделать. Заодно и checkstyle появится. У тебя много где 4 пробела за таб, мы на 2 пишем. В идее, вроде, можно это быстро поменять

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +                .withUserAgent("my service")
Можно вписать имя нашего сервиса, чтоб в api знали кто им трафик гонит :)

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ProfessionalEnvironmentDeserializer.java
> +        ProfessionalEnvironmentDto profEnv = new ProfessionalEnvironmentDto();
Опять сокращения :)

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/ProfessionalEnvironmentEntity.java
> +    public String getEnvName() {
Сокращения

2021-04-12 14:35 UTC, Azadios commented on backend/src/etc/hh-career-solution/jclient.properties
> +jclient.hostsWithSession=http://localhost
newline

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +        CompletableFuture<ProfessionalEnvironmentDto[]> profEnvDTOFuture = http.with(request)
Сокращения

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +        return profEnvDTOFuture.get();
Я не эксперт во фьючи, но, кажется, ты здесь никак её не используешь. Получаешь фьючу и сразу же блочишься на её выполнение. Если так и задумывалось, то можешь убрать бойлерплейт в виде переменной. @colorbash?

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ProfessionalEnvironmentDeserializer.java
> +        ObjectMapper objectMapper = new ObjectMapper();
Тож вынеси

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/ProfessionalEnvironmentEntity.java
> +public class ProfessionalEnvironmentEntity {
Он у тебя уже в пакете entity. Имхо, нет смысла добавлять Entity в название

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/ProfessionalEnvironmentEntity.java
> +        return Objects.hash(getId(), getEnvName());
Не обязательно всё делать через геттеры, если ты работаешь с местными полями. Можно и так, конечно

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/SpecializationEntity.java
> +    @Column(name = "laboring")
Можно не добавлять, если имена одинаковые

2021-04-12 14:35 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/SpecializationEntity.java
> +    @ManyToOne(fetch = FetchType.LAZY)
:+1:

2021-04-12 14:35 UTC, Azadios commented on backend/src/test/java/ru/hh/career/solution/parseProfEnvAndSpec/TestLoadPage.java
> +package ru.hh.career.solution.parseProfEnvAndSpec;
Пакет камелкейсом

2021-04-12 14:35 UTC, Azadios commented on backend/src/test/java/ru/hh/career/solution/parseProfEnvAndSpec/TestLoadPage.java
> +        URL url = new URL("https://api.hh.ru/specializations");
Адрес можно в статик константу

2021-04-12 14:35 UTC, Azadios commented on backend/src/test/java/ru/hh/career/solution/parseProfEnvAndSpec/TestLoadPage.java
> +}
Я так понимаю, тесты для того чтоб увидеть, что всё работает? Когда будешь финальную версию делать, можешь убрать, потому что в них не то чтоб прям много смысла :) Ну и на будущее через assert'ы даже для себя удобнее будет

2021-04-12 14:41 UTC, Azadios commented on backend/src/etc/hh-career-solution/jclient.properties
> +jclient.hostsWithSession=http://localhost
newline

2021-04-12 14:57 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/GenericDao.java
> +    protected void save(Object object) {
везде надо навесить `@Transactional`

2021-04-12 14:57 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/SpecializationDao.java
> +public class SpecializationDao extends GenericDao {
зачем extends GenericDaо ?

2021-04-12 14:57 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/SpecializationDao.java
> +public class SpecializationDao extends GenericDao {
GenericDao на то и генерик что может с любым Class<T> работать, получается что SpecializationDao и ProfessionalEnvironmentDao если не нужны спец запросы кроме crud-a

2021-04-12 14:57 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/SpecializationsDto.java
> +    private Integer idProfessionalEnvironment;
лучше id в конце переменной

2021-04-12 14:57 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +                    new HttpClientContext(Map.of(), Map.of(), List.of())), List.of())
а что это? Map.of(), Map.of(), List.of())), List.of()

2021-04-12 14:57 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +        return profEnvDTOFuture.get();
да можно убрать

2021-04-12 14:57 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +    public ProfessionalEnvironmentDto[] parse()
метод parse по сути скачивает реюме и десериализует, переназвать бы

2021-04-12 14:57 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +    public ProfessionalEnvironmentDto[] parse()
кстати где он вызывается?

2021-04-12 15:01 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/GenericDao.java
> +    protected void save(Object object) {
На уровне дао?

2021-04-12 15:02 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/SpecializationDao.java
> +public class SpecializationDao extends GenericDao {
Зато класс не надо будет передавать на месте вызова. + никто не говорит, что завтра SpecializationDao расширяться не будет. Не лучше сразу сделать прослойку между сервисом и GenericDao?

2021-04-12 17:02 UTC, Azadios requested changes

2021-04-12 17:02 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +    public ParserService(SessionFactory sessionFactory) {
У тебя сервис не зависит напрямую от SessionFactory. Ты его получаешь, чтобы пробросить его в Dao. Для этого есть спринг. Тебе нужен для сервиса Dao? Его и получай. Добавь аннотацию Inject и всё произойдёт само. Магия, не иначе :)

2021-04-12 17:02 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +            for (SpecializationsDto j: i.getSpecialization()){
Тож самое. getSpecialization возвращает коллекцию? Значит getSpecializations

2021-04-12 17:02 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +                SpecializationDao specializationDao = new SpecializationDao(sessionFactory);
Тож самое

2021-04-12 17:11 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/entity/ProfessionalEnvironmentEntity.java
> +    }
Да, забыл упомянуть. Hibernate требует для своей работы конструктор по умолчанию (это который без аргументов). Добавь его

2021-04-13 06:41 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/GenericDao.java
> +    protected void save(Object object) {
да, ты прав лучше на уровне сервиса, кстати работать(передавать по хттп и сохранять в базу) с коллекциями у нас принято батчами, можно тут попробовать это сделать, но не обязательно

2021-04-13 06:45 UTC, colorbash commented on backend/init.sql
> +  professional_environment_id INTEGER PRIMARY KEY,
когда ты пишешь "id as environment_id", это значит ты селектишь из нескольки таблиц и тебе бы хорошо понимать что откуда идет поэтому  у нас чачто делают `select pe.id from professional_environment pe`
а потом уже джоинят другие таблицы и вроде такая схема удобна

2021-04-13 06:46 UTC, colorbash commented on backend/init.sql
> +  professional_environment_id INTEGER PRIMARY KEY,
так что я бы оставил id, name

2021-04-13 06:47 UTC, colorbash commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/SpecializationDao.java
> +public class SpecializationDao extends GenericDao {
может тогда SpecializationDao и ProfessionalEnvironmentDao обьединить? уж очень близки сущности, всегда будут вместе использоваться

2021-04-13 07:00 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/GenericDao.java
> +    protected void save(Object object) {
Для такой ad-hoc задачи можно и забить, наверное. Но если в основном сервисе такая логика появится, то я за

2021-04-13 07:04 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dao/SpecializationDao.java
> +public class SpecializationDao extends GenericDao {
Да, наверное. Если разрастётся, то можно будет разсплитить обратно. Хотя тут, конечно, не оч, что они к разным таблицам обращаются. Имхо и так и так норм

2021-04-13 07:09 UTC, Azadios commented on backend/init.sql
> +  area_id     INTEGER PRIMARY KEY NOT NULL,
https://github.com/hhru/hh-career-solution/pull/9#discussion_r611217780

2021-04-13 17:41 UTC, Azadios reviewed
Уже прям совсем здорово. Допили то, что мы ещё до этого написали, раскидай по пакетам как договорились и можно мерджить

2021-04-13 17:41 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ProfessionalEnvironmentDeserializer.java
> +        SpecializationsDto[] specDTOS = mapper.readValue(treeNode.get("specializations").toString(), SpecializationsDto[].class);
Поменяй, пожалуйста, на камелкейс поменять
```suggestion
        SpecializationsDto[] specDtos = mapper.readValue(treeNode.get("specializations").toString(), SpecializationsDto[].class);
```
Ну и снова сокращения

2021-04-13 17:41 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ProfessionalEnvironmentDeserializer.java
> +        professionalEnvironmentDto.setSpecialization(Arrays.asList(specDTOS));
А сразу как лист нельзя получить из readValue? Я не помню, просто спрашиваю

2021-04-13 17:41 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +    public ParserService(ProfessionalEnvironmentDao professionalEnvironmentDao, SpecializationDao specializationDao) {
`@Inject` поставь плз

2021-04-13 17:41 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +@Singleton
Можно так не делать. Они по умолчанию синглтоны и их бины создаются, если заимпортить в Config. Про это чуть позже в слак напишу, разбираюсь как раз

2021-04-13 17:41 UTC, Azadios commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/services/ParserService.java
> +    @Transactional
Лучше на уровне сервиса. То есть над классом поставить. Тогда на все методы распространяется. В общем-то в классе с 1 методом пофиг, но зато сразу в глаза бросается, когда над классом написано

2021-04-13 18:24 UTC, BorisVeprintzev commented on backend/src/main/java/ru/hh/career/solution/professionalenvironmentandspecialization/dto/ParserProfessionalEnvironmentAndSpecialization.java
> +    public ProfessionalEnvironmentDto[] parse()
в ParserService

2021-04-15 15:17 UTC, BorisVeprintzev commented
разрешал конфликты и мог чего то напутать

2021-04-16 04:11 UTC, Azadios commented
Какой-то странный у тебя ребейс получился. +13к строк кода точно не должно быть. Давай лучше новый пр, чтоб было видно что именно сделано, а то тут в твой пр засчитывает изменения, которые уже в мастере

2021-04-16 10:30 UTC, closed without merging